import React, { useMemo, useState } from "react";
import { createRoot } from "react-dom/client";
import { Brain, CheckCircle2, ChevronLeft, ChevronRight, ClipboardList, Database, FileUp, Gauge, GraduationCap, Home, RotateCcw, Settings, ShieldCheck, Sparkles, Upload } from "lucide-react";
import "./styles.css";

const initialQuestions = [
  { id:1, grade:"八年級", subject:"生活科技", unit:"能源與生活", type:"單選題", difficulty:"基礎", text:"下列哪一項最符合「再生能源」的定義？", options:["石油","天然氣","太陽能","煤炭"], answer:2, explanation:"太陽能可透過自然過程持續補充，屬於再生能源；石油、天然氣與煤炭屬於化石燃料。" },
  { id:2, grade:"八年級", subject:"生活科技", unit:"設計與製作", type:"單選題", difficulty:"基礎", text:"在產品設計流程中，最重要的第一步通常是什麼？", options:["直接製作成品","了解需求與問題","大量生產","進行產品宣傳"], answer:1, explanation:"設計通常從理解使用者需求、界定問題開始，才能提出適切的解決方案。" },
  { id:3, grade:"七年級", subject:"自然", unit:"科學探究", type:"單選題", difficulty:"中等", text:"若要研究不同光照時間對植物生長的影響，哪一項最適合作為自變因？", options:["植物高度","光照時間","植物種類","土壤種類"], answer:1, explanation:"研究者主動改變的因素是自變因，因此本題為光照時間。" },
  { id:4, grade:"九年級", subject:"數學", unit:"一元一次方程式", type:"單選題", difficulty:"基礎", text:"若 2x + 5 = 15，則 x 等於多少？", options:["3","5","7","10"], answer:1, explanation:"2x + 5 = 15，先減去 5 得 2x = 10，再除以 2 得 x = 5。" }
];

function App(){
  const [view,setView]=useState("home"); const [questions,setQuestions]=useState(initialQuestions); const [quizIndex,setQuizIndex]=useState(0); const [answers,setAnswers]=useState({}); const [showResult,setShowResult]=useState(false); const [filters,setFilters]=useState({grade:"全部",subject:"全部"}); const [uploadMessage,setUploadMessage]=useState("");
  const filtered=useMemo(()=>questions.filter(q=>(filters.grade==="全部"||q.grade===filters.grade)&&(filters.subject==="全部"||q.subject===filters.subject)),[questions,filters]);
  const quizPool=filtered.length?filtered:questions; const current=quizPool[quizIndex]; const score=quizPool.reduce((s,q)=>s+(answers[q.id]===q.answer?1:0),0);
  const startQuiz=()=>{setQuizIndex(0);setAnswers({});setShowResult(false);setView("quiz")};
  const choose=i=>setAnswers(a=>({...a,[current.id]:i}));
  const next=()=>quizIndex<quizPool.length-1?setQuizIndex(i=>i+1):setShowResult(true); const prev=()=>{if(quizIndex>0)setQuizIndex(i=>i-1)};
  const handleUpload=e=>{const file=e.target.files?.[0];if(file)setUploadMessage(`已選取「${file.name}」。目前建立匯入佇列，正式版可接 PDF／Word／Excel 解析與 OCR。`)};
  return <div className="app"><header className="topbar"><button className="brand" onClick={()=>setView("home")} aria-label="回到首頁"><span className="brandIcon"><GraduationCap size={24}/></span><span><strong>後甲國中學習測驗平台</strong><small>國中互動式題庫</small></span></button><nav aria-label="主要導覽"><button className={view==="home"?"active":""} onClick={()=>setView("home")}><Home size={18}/>學生首頁</button><button className={view==="bank"?"active":""} onClick={()=>setView("bank")}><Database size={18}/>題庫管理</button><button className={view==="admin"?"active":""} onClick={()=>setView("admin")}><Settings size={18}/>教師後台</button></nav></header><main>
    {view==="home"&&<HomeView filters={filters} setFilters={setFilters} questions={questions} startQuiz={startQuiz}/>} {view==="quiz"&&<QuizView current={current} index={quizIndex} total={quizPool.length} answers={answers} choose={choose} prev={prev} next={next} showResult={showResult} score={score} restart={startQuiz} goHome={()=>setView("home")} pool={quizPool}/>} {view==="bank"&&<BankView questions={questions} filters={filters} setFilters={setFilters}/>} {view==="admin"&&<AdminView questions={questions} uploadMessage={uploadMessage} handleUpload={handleUpload} goBank={()=>setView("bank")} addDemo={()=>{setQuestions(q=>[...q,{...initialQuestions[0],id:Date.now(),text:"下列哪一項最能展現「設計思考」的精神？",options:["只照抄既有產品","先了解使用者需求再反覆測試","只追求外觀","完全不進行測試"],answer:1,explanation:"設計思考重視理解需求、提出方案、製作原型與反覆測試。"}]);setUploadMessage("已新增一題示範題。")}}/>}
  </main><footer>© 2026 後甲國中學習測驗平台 · WCAG 2.2 AA 導向 · MVP</footer></div>
}
function HomeView({filters,setFilters,questions,startQuiz}){const subjects=[...new Set(questions.map(q=>q.subject))];const count=questions.filter(q=>(filters.grade==="全部"||q.grade===filters.grade)&&(filters.subject==="全部"||q.subject===filters.subject)).length;return <section className="container"><div className="hero"><div><span className="eyebrow"><Sparkles size={16}/>從基本概念開始，逐步建立學習信心</span><h1>今天想練習什麼？</h1><p>選擇年級與科目，開始簡潔、容易操作的互動式測驗。</p></div><div className="heroBadge"><ShieldCheck size={22}/><span>無障礙友善<br/><b>AA 導向</b></span></div></div><div className="selection card"><h2>選擇測驗範圍</h2><label>年級<select value={filters.grade} onChange={e=>setFilters({...filters,grade:e.target.value})}><option>全部</option><option>七年級</option><option>八年級</option><option>九年級</option></select></label><label>科目<select value={filters.subject} onChange={e=>setFilters({...filters,subject:e.target.value})}><option>全部</option>{subjects.map(s=><option key={s}>{s}</option>)}</select></label><div className="rangeInfo"><ClipboardList size={20}/><div><b>{count} 題可練習</b><span>系統會依目前條件使用題庫</span></div></div><button className="primary large" onClick={startQuiz} disabled={!count}>開始測驗 <ChevronRight size={20}/></button></div><div className="featureGrid"><Feature icon={<Brain/>} title="基本概念診斷" text="透過答題表現找出需要再次複習的觀念。"/><Feature icon={<RotateCcw/>} title="錯題再練習" text="測驗完成後快速回顧與重新挑戰。"/><Feature icon={<Gauge/>} title="清楚的學習回饋" text="不只顯示分數，也提供每題解析。"/></div></section>}
function Feature({icon,title,text}){return <article className="feature card"><div className="featureIcon">{icon}</div><h3>{title}</h3><p>{text}</p></article>}
function QuizView({current,index,total,answers,choose,prev,next,showResult,score,restart,goHome,pool}){if(showResult)return <section className="container resultPage"><div className="resultCard card"><div className="resultIcon"><CheckCircle2 size={42}/></div><p className="eyebrow">測驗完成</p><h1>{Math.round(score/total*100)} 分</h1><p className="resultSub">答對 {score} / {total} 題</p><div className="resultStats"><div><b>{score}</b><span>答對</span></div><div><b>{total-score}</b><span>待複習</span></div><div><b>{total}</b><span>總題數</span></div></div><h2>錯題檢視</h2><div className="reviewList">{pool.filter(q=>answers[q.id]!==q.answer).map(q=><div className="reviewItem" key={q.id}><b>第 {q.id} 題</b><span>{q.text}</span><em>正解：{q.options[q.answer]}｜{q.explanation}</em></div>)}</div>{score===total&&<p className="successMessage">全部答對，太棒了！</p>}<div className="actions"><button className="secondary" onClick={goHome}>回首頁</button><button className="primary" onClick={restart}>再測一次</button></div></div></section>;return <section className="container quizPage"><div className="quizHeader"><div><span className="eyebrow">{current.subject} · {current.grade} · {current.unit}</span><h1>互動式測驗</h1></div><div className="progressText">第 <b>{index+1}</b> / {total} 題</div></div><div className="progressBar" role="progressbar" aria-valuemin="1" aria-valuemax={total} aria-valuenow={index+1} aria-label={`測驗進度 ${index+1} / ${total}`}><span style={{width:`${(index+1)/total*100}%`}}/></div><article className="questionCard card"><div className="questionMeta"><span>{current.type}</span><span>{current.difficulty}</span></div><h2>{current.text}</h2><fieldset><legend className="srOnly">請選擇一個答案</legend>{current.options.map((opt,i)=><label key={opt} className={`option ${answers[current.id]===i?"selected":""}`}><input type="radio" name={`answer-${current.id}`} checked={answers[current.id]===i} onChange={()=>choose(i)}/><span className="letter">{String.fromCharCode(65+i)}</span><span>{opt}</span></label>)}</fieldset><div className="quizActions"><button className="secondary" onClick={prev} disabled={index===0}><ChevronLeft/>上一題</button><button className="primary" onClick={next} disabled={answers[current.id]===undefined}>{index===total-1?"完成測驗":"下一題"}<ChevronRight/></button></div></article><p className="accessNote"><ShieldCheck size={17}/> 可使用鍵盤 Tab 操作；答案選項同時提供文字與焦點狀態，不依賴顏色辨識。</p></section>}
function BankView({questions,filters,setFilters}){const list=questions.filter(q=>(filters.grade==="全部"||q.grade===filters.grade)&&(filters.subject==="全部"||q.subject===filters.subject));return <section className="container"><div className="pageTitle"><span className="eyebrow"><Database size={16}/>題庫</span><h1>題目管理</h1><p>目前共有 {questions.length} 題。</p></div><div className="toolbar card"><label>年級<select value={filters.grade} onChange={e=>setFilters({...filters,grade:e.target.value})}><option>全部</option><option>七年級</option><option>八年級</option><option>九年級</option></select></label><label>科目<select value={filters.subject} onChange={e=>setFilters({...filters,subject:e.target.value})}><option>全部</option>{[...new Set(questions.map(q=>q.subject))].map(s=><option key={s}>{s}</option>)}</select></label></div><div className="tableWrap card"><table><caption className="srOnly">題庫清單</caption><thead><tr><th>題號</th><th>年級</th><th>科目</th><th>單元</th><th>難度</th><th>題型</th></tr></thead><tbody>{list.map(q=><tr key={q.id}><td><b>#{q.id}</b></td><td>{q.grade}</td><td>{q.subject}</td><td>{q.unit}</td><td><span className="tag">{q.difficulty}</span></td><td>{q.type}</td></tr>)}</tbody></table></div></section>}
function AdminView({questions,uploadMessage,handleUpload,goBank,addDemo}){return <section className="container"><div className="pageTitle"><span className="eyebrow"><Settings size={16}/>教師後台</span><h1>建立與管理測驗</h1><p>將考古題整理成可重複使用的線上題庫。</p></div><div className="adminGrid"><article className="uploadCard card"><div className="uploadIcon"><FileUp size={32}/></div><h2>上傳考古題</h2><p>支援 PDF、Word、Excel 等檔案。MVP 提供匯入佇列介面。</p><label className="uploadButton"><Upload size={18}/>選擇檔案<input type="file" accept=".pdf,.doc,.docx,.xls,.xlsx,.csv" onChange={handleUpload}/></label>{uploadMessage&&<div className="notice" role="status">{uploadMessage}</div>}</article><article className="card adminList"><h2>快速操作</h2><button className="adminAction" onClick={goBank}><Database/><span><b>查看題庫</b><small>{questions.length} 題</small></span><ChevronRight/></button><button className="adminAction" onClick={addDemo}><Sparkles/><span><b>新增示範題</b><small>測試題庫流程</small></span><ChevronRight/></button><div className="workflow"><b>建議匯入流程</b><span>① 上傳檔案</span><span>② AI／OCR 解析</span><span>③ 教師確認</span><span>④ 發布至題庫</span></div></article></div><div className="accessCard card"><ShieldCheck/><div><b>無障礙 AA 檢核方向</b><p>語意化 HTML、鍵盤操作、清楚 Focus、表單 Label、非色彩唯一資訊、適當對比與可讀文字。</p></div></div></section>}
createRoot(document.getElementById("root")).render(<App/>);
