import React, { useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { BookOpen, CheckCircle2, ClipboardList, FileUp, Home, LayoutDashboard, Plus, Search, Settings, ShieldCheck, Upload, XCircle } from 'lucide-react';
import './styles.css';

const seed = [
 {id:1,grade:'七年級',subject:'自然',unit:'科學探究',type:'單選題',text:'研究不同光照時間對植物生長的影響，哪一項是自變因？',options:['植物高度','光照時間','植物種類','土壤種類'],answer:1,explanation:'研究者主動改變的因素是自變因。'},
 {id:2,grade:'八年級',subject:'生活科技',unit:'設計與製作',type:'單選題',text:'產品設計流程通常應先做什麼？',options:['直接製作','了解需求與問題','大量生產','宣傳產品'],answer:1,explanation:'設計應先理解使用者需求並界定問題。'},
 {id:3,grade:'八年級',subject:'生活科技',unit:'能源與生活',type:'單選題',text:'下列何者屬於再生能源？',options:['石油','煤炭','太陽能','天然氣'],answer:2,explanation:'太陽能可由自然過程持續補充。'},
 {id:4,grade:'九年級',subject:'數學',unit:'一元一次方程式',type:'單選題',text:'若 2x + 5 = 15，x 等於多少？',options:['3','5','7','10'],answer:1,explanation:'先減 5 得 2x=10，再除以 2 得 x=5。'}
];

function App(){
 const [page,setPage]=useState('home'); const [questions,setQuestions]=useState(seed); const [grade,setGrade]=useState('全部'); const [subject,setSubject]=useState('全部'); const [index,setIndex]=useState(0); const [answers,setAnswers]=useState({}); const [done,setDone]=useState(false); const [flags,setFlags]=useState({}); const [upload,setUpload]=useState('');
 const list=useMemo(()=>questions.filter(q=>(grade==='全部'||q.grade===grade)&&(subject==='全部'||q.subject===subject)),[questions,grade,subject]);
 const pool=list.length?list:questions; const current=pool[index]; const score=pool.filter(q=>answers[q.id]===q.answer).length;
 const start=()=>{setIndex(0);setAnswers({});setFlags({});setDone(false);setPage('quiz')};
 const addQuestion=()=>{setQuestions(q=>[...q,{...seed[0],id:Math.max(...q.map(x=>x.id))+1,text:'下列哪一項最符合設計思考的精神？',options:['照抄既有產品','了解需求並反覆測試','只追求外觀','完全不測試'],answer:1,explanation:'設計思考重視需求、原型與反覆測試。'}]);setUpload('已新增示範題，可至題庫查看。')};
 return <div className="app"><header><button className="brand" onClick={()=>setPage('home')}><span className="logo"><BookOpen/></span><span><b>後甲國中</b><small>線上測驗系統</small></span></button><nav><button className={page==='home'?'active':''} onClick={()=>setPage('home')}><Home/>學生首頁</button><button className={page==='bank'?'active':''} onClick={()=>setPage('bank')}><ClipboardList/>題庫</button><button className={page==='teacher'?'active':''} onClick={()=>setPage('teacher')}><Settings/>教師後台</button></nav></header><main>{page==='home'&&<Home list={list} grade={grade} setGrade={setGrade} subject={subject} setSubject={setSubject} start={start} questions={questions}/>} {page==='quiz'&&<Quiz current={current} index={index} pool={pool} answers={answers} setAnswers={setAnswers} flags={flags} setFlags={setFlags} done={done} setDone={setDone} score={score} start={start} home={()=>setPage('home')}/>} {page==='bank'&&<Bank questions={questions} grade={grade} setGrade={setGrade} subject={subject} setSubject={setSubject}/>} {page==='teacher'&&<Teacher questions={questions} upload={upload} setUpload={setUpload} addQuestion={addQuestion} goBank={()=>setPage('bank')}/>}</main><footer><ShieldCheck/> 以學習為核心 · 支援鍵盤操作與響應式介面</footer></div>;
}
function Filters({grade,setGrade,subject,setSubject,questions}){return <div className="filters"><label>年級<select value={grade} onChange={e=>setGrade(e.target.value)}><option>全部</option><option>七年級</option><option>八年級</option><option>九年級</option></select></label><label>科目<select value={subject} onChange={e=>setSubject(e.target.value)}><option>全部</option>{[...new Set(questions.map(q=>q.subject))].map(s=><option key={s}>{s}</option>)}</select></label></div>}
function Home({list,grade,setGrade,subject,setSubject,start,questions}){return <section className="container"><div className="hero"><div><span className="eyebrow">✦ Clean Modern Learning</span><h1>今天想練習什麼？</h1><p>選擇年級與科目，立即開始互動式測驗。</p></div><div className="heroMark"><BookOpen size={44}/><b>{questions.length}</b><span>題示範題庫</span></div></div><div className="card selection"><h2>選擇測驗範圍</h2><Filters grade={grade} setGrade={setGrade} subject={subject} setSubject={setSubject} questions={questions}/><div className="count"><ClipboardList/>目前可練習 <b>{list.length||questions.length}</b> 題</div><button className="primary" onClick={start}>開始測驗 →</button></div><div className="features"><article className="card"><LayoutDashboard/><h3>清楚進度</h3><p>每題必答，進度條與題號導覽一目了然。</p></article><article className="card"><CheckCircle2/><h3>即時回饋</h3><p>完成後查看分數、錯題與解析。</p></article><article className="card"><BookOpen/><h3>持續複習</h3><p>題庫可依年級與科目篩選。</p></article></div></section>}
function Quiz({current,index,pool,answers,setAnswers,flags,setFlags,done,setDone,score,start,home}){if(done)return <section className="container result"><div className="card resultCard"><CheckCircle2 size={54}/><span className="eyebrow">測驗完成</span><h1>{Math.round(score/pool.length*100)} 分</h1><p>答對 {score} / {pool.length} 題</p><div className="review">{pool.filter(q=>answers[q.id]!==q.answer).map(q=><div key={q.id}><b>第 {q.id} 題</b><p>{q.text}</p><span>正解：{q.options[q.answer]}｜{q.explanation}</span></div>)}</div><button className="primary" onClick={start}>再測一次</button><button className="secondary" onClick={home}>回首頁</button></div></section>;
 return <section className="container quiz"><div className="quizTop"><span className="eyebrow">{current.subject} · {current.grade}</span><b>第 {index+1} / {pool.length} 題</b></div><div className="progress"><span style={{width:`${(index+1)/pool.length*100}%`}}/></div><article className="card question"><div className="questionMeta"><span>{current.type}</span><button className="flag" onClick={()=>setFlags(f=>({...f,[current.id]:!f[current.id]}))}>{flags[current.id]?'已標記':'標記題目'}</button></div><h2>{current.text}</h2><fieldset>{current.options.map((o,i)=><label className={answers[current.id]===i?'option selected':'option'} key={o}><input type="radio" name={`q${current.id}`} checked={answers[current.id]===i} onChange={()=>setAnswers(a=>({...a,[current.id]:i}))}/><b>{String.fromCharCode(65+i)}</b>{o}</label>)}</fieldset><div className="actions"><button className="secondary" disabled={!index} onClick={()=>setIndex(i=>i-1)}>← 上一題</button><button className="primary" disabled={answers[current.id]===undefined} onClick={()=>index===pool.length-1?setDone(true):setIndex(i=>i+1)}>{index===pool.length-1?'完成測驗':'下一題 →'}</button></div></article></section>}
function Bank({questions,grade,setGrade,subject,setSubject}){const [search,setSearch]=useState('');const list=questions.filter(q=>(grade==='全部'||q.grade===grade)&&(subject==='全部'||q.subject===subject)&&q.text.includes(search));return <section className="container"><div className="pageTitle"><span className="eyebrow">題庫管理</span><h1>所有題目</h1><p>共 {questions.length} 題</p></div><div className="card toolbar"><Filters {...{grade,setGrade,subject,setSubject,questions}}/><label className="search"><Search/><input placeholder="搜尋題目內容" value={search} onChange={e=>setSearch(e.target.value)}/></label></div><div className="card tableWrap"><table><thead><tr><th>題號</th><th>年級</th><th>科目</th><th>題目</th></tr></thead><tbody>{list.map(q=><tr key={q.id}><td>#{q.id}</td><td>{q.grade}</td><td>{q.subject}</td><td>{q.text}</td></tr>)}</tbody></table></div></section>}
function Teacher({questions,upload,setUpload,addQuestion,goBank}){return <section className="container"><div className="pageTitle"><span className="eyebrow">教師端</span><h1>題庫工作台</h1><p>上傳文件、建立題目並管理題庫。</p></div><div className="teacherGrid"><article className="card upload"><FileUp size={40}/><h2>文件上傳</h2><p>支援 PDF、DOCX、ZIP、TXT、Markdown。此版本提供前端匯入流程預覽。</p><label className="uploadBtn"><Upload/>選擇文件<input type="file" accept=".pdf,.docx,.zip,.txt,.md" onChange={e=>setUpload(e.target.files?.[0]?`已選取：${e.target.files[0].name}。待接入 Supabase Storage 與 AI 解析。`:'')}/></label>{upload&&<div className="notice">{upload}</div>}</article><article className="card"><h2>快速操作</h2><button className="actionRow" onClick={goBank}><ClipboardList/>查看題庫 <b>→</b></button><button className="actionRow" onClick={addQuestion}><Plus/>新增示範題 <b>→</b></button><div className="workflow"><b>正式版流程</b><span>1. 上傳原始文件</span><span>2. 文字抽取與 AI 結構化</span><span>3. 教師人工審核</span><span>4. 發布至學生端</span></div></article></div></section>}

createRoot(document.getElementById('root')).render(<App/>);
